# only run for: merge commits, releases and pull-requests
if: type != push OR branch = master OR branch =~ /^\d+\.\d+(\.\d+)?(-\S*)?$/

os: osx
osx_image: xcode10.1
language: swift
xcode_project: LegibleError.xcodeproj
xcode_scheme: LegibleError-Package

jobs:
  include:
    - name: macOS / Swift 4.0.3 (Xcode 10.1)
      stage: test
      script: swift test --parallel -Xswiftc -swift-version -Xswiftc 4 -Xswiftc -warnings-as-errors

    - name: macOS / Swift 4.2.1 (Xcode 10.1)
      script: swift test --parallel -Xswiftc -warnings-as-errors

    - name: macOS / Swift 5.0.1 (Xcode 10.2)
      script: swift test --parallel  -Xswiftc -warnings-as-errors
