name: CI
on: [pull_request]
jobs:
  smoke:
    runs-on: macos-latest
    steps:
    - uses: technote-space/auto-cancel-redundant-job@v1
    - uses: actions/checkout@v2
    - run: swift test --generate-linuxmain
    - run: git diff --exit-code
  macOS:
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode:
      # -  10.3  # Swift 5.0  # fails mysteriously
        -  11.3  # Swift 5.1
        - ^11.4  # Swift 5.2
        -  12.4  # Swift 5.3
      # -  12.5  # Swift 5.4  # not yet available
    steps:
    - uses: actions/checkout@v2
    - name: setup-xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - run: swift test --parallel -Xswiftc -warnings-as-errors
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
        - 4.2.1
        - 5.0.3
        - 5.1.5
        - 5.2.5
        - 5.3.3
        - 5.4.1
    container:
      image: swift:${{ matrix.swift }}
    steps:
    - uses: actions/checkout@v2
    - run: swift test --parallel -Xswiftc -warnings-as-errors
