on:
  pull_request:
    paths:
      - Sources/**
      - Tests/**
      - .github/workflows/ci.yml
  schedule:
    - cron: '3 3 * * 2'  # 3:03 AM, every Tuesday
jobs:
  macOS:
    runs-on: macos-latest
    strategy:
      matrix:
        swift:
        - ~5.0
        - ~5.1
        - ~5.2
        - ~5.3
        - ~5.4
    steps:
    - uses: actions/checkout@v2
    - uses: mxcl/xcodebuild@v1
      with:
        swift: ${{ matrix.swift }}
        warnings-as-errors: true
      continue-on-error: ${{ matrix.swift == '~5.4' }}
    - run: |
        swift test --generate-linuxmain
        git diff --exit-code
      if: ${{ matrix.swift == '~5.3' }}
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
        - '4.2'
        - '5.0'
        - '5.1'
        - '5.2'
        - '5.3'
        - '5.4'
    container:
      image: swift:${{ matrix.swift }}
    steps:
    - uses: actions/checkout@v2
    - run: swift test --parallel -Xswiftc -warnings-as-errors
