on:
  pull_request:
    paths:
      - Sources/**
      - Tests/**
      - .github/workflows/ci.yml
  schedule:
    - cron: '3 3 * * 2'  # 3:03 AM, every Tuesday
jobs:
  macOS:
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode:
      # -  10.3  # Swift 5.0  # fails mysteriously
        -  11.3  # Swift 5.1
        - ^11.4  # Swift 5.2
        -  12.4  # Swift 5.3
      # -  12.5  # Swift 5.4  # not yet available
    steps:
    - uses: actions/checkout@v2
    - name: setup-xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - run: swift test --parallel -Xswiftc -warnings-as-errors
    - run: |
        swift test --generate-linuxmain
        git diff --exit-code
      if: ${{ matrix.xcode == '12.4' }}
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
        - '4.2'
        - '5.0'
        - '5.1'
        - '5.2'
        - '5.3'
        - '5.4'
    container:
      image: swift:${{ matrix.swift }}
    steps:
    - uses: actions/checkout@v2
    - run: swift test --parallel -Xswiftc -warnings-as-errors
