on:
  pull_request:
    paths:
      - Sources/**
      - Tests/**
      - .github/workflows/ci.yml
  schedule:
    - cron: '3 3 * * 2'  # 3:03 AM, every Tuesday
jobs:
  macOS:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        swift:
        - ~5.0
        - ~5.1
        - ~5.2
        - ~5.3
        os:
        - macos-10.15
        include:
        - swift: 5.4
          os: macos-11
        - swift: 5.5
          os: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: mxcl/xcodebuild@v1
      with:
        swift: ${{ matrix.swift }}
        warnings-as-errors: true
    - run: |
        swift test --generate-linuxmain
        git diff --exit-code
      if: ${{ matrix.swift == '5.3' }}
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
        - swift:4.2
        - swift:5.0
        - swift:5.1
        - swift:5.2
        - swift:5.3
        - swift:5.4
        - swiftlang/swift:nightly-5.5
    container:
      image: ${{ matrix.swift }}
    steps:
    - uses: actions/checkout@v2
    - run: swift test --parallel -Xswiftc -warnings-as-errors
