name: CI
on: 
  push:
    branches:
    - master
jobs:
  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: .build
        key: macOS-
        restore-keys: macOS-
    - run: swift build
      env:
        DEVELOPER_DIR: /Applications/Xcode_11.5.app
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
        - 4.2.1
        - 5.0.3
        - 5.1.4
        - 5.2.4
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: .build
        key: swift-${{ matrix.swift }}
        restore-keys: swift-
    - uses: YOCKOW/Action-setup-swift@master
      if: ${{ matrix.swift != '5.2.4' }}
      with:
        swift-version: ${{ matrix.swift }}
    - run: swift build
